### ISSUE TITLE
Duplicate ps when building Hetu

### ISSUE THREAD

**Issue by HPFilter** [Hsword/Hetu#24]
Hello,
I tried to build Hetu with cmake 3.18.2. However, I got following errors after executing cmake.
![20220208220446](https://user-images.githubusercontent.com/52553906/153003785-c04c9451-e9d2-4b58-b4cf-a5e5af61e7e7.jpg)

It seems that this was caused by the target "ps" with the same name in Hetu and HetuML. Is there any method to successfully build Hetu without this problem?

Best regards
Xiaodian

**Comment by Hsword** [comment]
Could you please try to set "HETU_ML" and "HETU_PARALLEL_ML" to "OFF" in cmake/config.cmake?

**Comment by HPFilter** [comment]
Thanks for your reply.
After modifying the settings according to your advice, the project can be built without error.
However, we have some problems when running the examples of ctr models. 
![image](https://user-images.githubusercontent.com/52553906/153128980-ca481c02-57bd-4ebb-9dad-79acbe5590f2.png)
As I am using the conda environment of Hetu, I'm wondering where the problem's coming from.
Thank you very much.

**Comment by HugoZHL** [comment]
Please try this PR: https://github.com/Hsword/Hetu/pull/25, which can solve problems for running wdl adult tests.

**Comment by HPFilter** [comment]
Thanks for the update.
The execution of local_wdl_adult is successful with the PR.
However, both ps and hybrid mode raise the error as follows and the program also gets stuck. (for clear display, the number of workers is set to 2).
![image](https://user-images.githubusercontent.com/52553906/153164788-d049d7ef-0c6f-4ed8-8657-68cd92b740b0.png)

**Comment by HugoZHL** [comment]
Please try `mkdir logs` before running scripts; or not specify  `log_path` when initiating executor.

**Comment by HPFilter** [comment]
Sorry for so many questions. But there seems to be other errors in the distributed example.
The error messages are no longer raised after making the directory logs. But the program is still stucked.
I added some log information in the program to find where the program gets stucked. And it turns out to be the function _worker_init_ in the file _executor.py_.
![image](https://user-images.githubusercontent.com/52553906/153194194-1eafb1f3-6fed-4d9a-bded-00d4bf13a785.png)

Therefore, I looked at the file _python_binding.cc_ in directory Hetu/ps-lite/src where function Init is declared and further located the function Start.
![image](https://user-images.githubusercontent.com/52553906/153198508-749b6b47-a05f-4fa6-a1fa-fce16de119e5.png)

Function Start is declared in _ps.h_ and it further calls the function Postoffice::Start in file _postoffice.cc_. Several lockers are used in this function. I added some debug information in the function as follows.
![image](https://user-images.githubusercontent.com/52553906/153199423-7da4dd26-ff09-4c9c-b727-dc0b8f25e342.png)

The debug information is printed as follows.
![image](https://user-images.githubusercontent.com/52553906/153200184-52de7662-f51d-495e-9be2-ce84267d328d.png)

It can be inferred from the debug information that function Init() is totally called three times by function server_init(), scheduler_init() and worker_init() in file _executor.py_ separately. And all of them are stuck in the function Barrier(). 

Is there any possible reason to cause such problem?

**Comment by HugoZHL** [comment]
Have you killed all the previously launched python processes before launching new tasks? Some server processes may not exit normally during exceptions, and they will occupy the ports. Please use `bash kill.sh` to kill all the python processes.

**Comment by HPFilter** [comment]
The problem is solved after killing the processes and the distributed examples can be executed now.
Thanks a lot for all of your help.
