### ISSUE TITLE
Get stuck when launching the server in hybrid mode

### ISSUE THREAD

**Issue by HPFilter** [Hsword/Hetu#27]
Hello,
I was trying to run hetu in hybrid mode with multiple nodes.
My command to launch the server and scheduler is
_python -m hetu.launcher ${workdir}/../settings/local_s1.yml -n 1 --sched_

and the content of yml file is as follows.
![image](https://user-images.githubusercontent.com/52553906/156574276-9057b24b-9b41-4383-b542-b224f856f96a.png)

However, both the scheduler and server processes are stuck in the following loop (Line 357 in the file ps-lite/src/van.cc).
![image](https://user-images.githubusercontent.com/52553906/156574818-f8efa31a-50bc-4e69-b993-33783a79d9a2.png)

Without shutting down the previous program, I started the worker and it could not find the server.
![image](https://user-images.githubusercontent.com/52553906/156575612-c1318a74-823f-46fb-9da9-e55c763d0439.png)

My workers and server are located in the same machine.
I wonder is there anything wrong with my configurations or did I miss any preceding steps?

Thank you very much.

**Comment by HugoZHL** [comment]
It's normal that the scheduler and the servers will wait for the workers.
Now we use `heturun` command to launch distributed tasks. Please refer to https://github.com/Hsword/Hetu/pull/25 which provides an example of `heturun`.
