### ISSUE TITLE
Nice Dropout CUDA Kernel Implement

### ISSUE THREAD

**Issue by MARD1NO** [Hsword/Hetu#32]
modify from oneflow?

https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/user/kernels/dropout_kernel.cu#L128-L190

https://github.com/Hsword/Hetu/blob/main/src/ops/Dropout.cu#L42-L87

**Comment by Hsword** [comment]
Sorry for the unexpected PR merge. We have rollback the code version.
