### ISSUE TITLE
fatal error: cub/cub.cuh: No such file or directory

### ISSUE THREAD

**Issue by lmohit95** [Hsword/Hetu#48]
I am trying to setup Hetu with CUDA 10.2. I have followed all the steps provided in the README.MD, but I am facing an issue while performing the `make -j 8` step. I have installed CUB from https://github.com/NVIDIA/cub/releases/tag/1.12.1 and used appropriate path in cmake.config file. However, I always get an error saying `fatal error: cub/cub.cuh: No such file or directory`.

<img width="1162" alt="Hetu_Error" src="https://user-images.githubusercontent.com/89669946/201509597-c10f13a6-0082-4974-857a-bdd33be3f740.png">

Is it possible to attach a sample cmake.config file for reference?

**Comment by Hankpipi** [comment]
Hi @lmohit95, this may be a feasible way to solve this problem:
```bash
mv cub-1.12.1/cub  /usr/local/cuda/include
```
Run this script in the folder where you unzipped the `cub-1.12.1.zip` before performing the `make -j 8` step. In this way, it will not be requisite to modify `cmake.config`.

**Comment by lmohit95** [comment]
Thanks a lot. It worked.
