### ISSUE TITLE
I can't find source code about Automatic Distributed Training, i.e. Cost estimation

### ISSUE THREAD

**Issue by CjhHa1** [Hsword/Hetu#68]
In your latest doc [doc]( https://hetu-doc.readthedocs.io/en/latest/Features/content1/#automatic-distributed-training), you mentioned that  you have achieved many distributed training features. However I can not find them, especially for cost estimation. I need help.

**Comment by Hsword** [comment]
Thanks for your interests. Currently, we only provide tutorials for regular system users, e.g., someone who wants to use Hetu to perform efficient distributed DL training.

It's not very clear which part of our system you are interested in. But if you are a DL system developer who wants to join us, the best way to contact us is via email. We welcome any kinds of collaborations on Hetu.

**Comment by CjhHa1** [comment]
> 

hi, I've sent an email to you but I did not get a reply

**Comment by Hsword** [comment]
The profiler in Hetu is here: [python/hetu/profiler](https://github.com/Hsword/Hetu/blob/main/python/hetu/profiler.py), which can be used to estimate the cost.
Recently, Hetu has also released another easy-to-use automatic distributed training system [Galvatron](https://github.com/Hsword/Hetu/tree/main/tools/Galvatron) for PyTorch users. I suggest to taking a look at it and I think it would be much more easier for you to understand.
