### ISSUE TITLE
Questions about some specific numbers in Galvatron.

### ISSUE THREAD

**Issue by haolin-nju** [Hsword/Hetu#70]
I notice that there exists some specific numbers in Galvatron when searching for the optimal strategy. For example, in [tools/Galvatron/bert/search_layerwise_hp_8gpus.py#L77~88](https://github.com/Hsword/Hetu/blob/main/tools/Galvatron/bert/search_layerwise_hp_8gpus.py#L77), the `parameter_size` of BERT-Large is designated as 48.05, `tp_activation_per_bsz_dict` is designated as a constant dict, and `other_model_states` and `other_activation_per_bsz` are designated with two constants. I'd like to raise another example, in [tools/Galvatron/bert/search_layerwise_hp_dist_16gpus.py#L93~94](https://github.com/Hsword/Hetu/blob/main/tools/Galvatron/bert/search_layerwise_hp_dist_16gpus.py#L93), there are two constant dicts called `other_memory_pp_off` and `other_memory_pp_on`. I'm wondering that how these numbers are obtained? Are there any scripts or formulations for accessing these constants? Moreover, BERT-Large has about 340M parameters in common sense, so I'm also confused about how 48.05 is obtained in Galvatron.

It would be of great help if you address the above questions. Many thanks!

**Comment by AFDWang** [comment]
In this old version, parameter_size 48.05 is obtained by manual profiling, which indicates the memory cost of the parameter size in one Bert-Large layer is 48.05 MB. 
We will be releasing a new version of Galvatron in the coming weeks, which contains automatic profiling scripts that profiles the memory consumption and computation cost of any given model automatically.

**Comment by haolin-nju** [comment]
> In this old version, parameter_size 48.05 is obtained by manual profiling, which indicates the memory cost of the parameter size in one Bert-Large layer is 48.05 MB. We will be releasing a new version of Galvatron in the coming weeks, which contains automatic profiling scripts that profiles the memory consumption and computation cost of any given model automatically.

Thank you for your reply! I'm looking forward to the release of the new Galvatron version.

**Comment by haolin-nju** [comment]
Hi, I have questions about some specific numbers in the cost model now. For example, in [tools/Galvatron/utils/cost_model_dist.py#L174~L175](https://github.com/Hsword/Hetu/blob/6a501c9a57b036c19341122668e5678b55881173/tools/Galvatron/utils/cost_model_dist.py#L174), `self.bct` is multiplied by 2/3 and 1/3, respectively. It seems to indicate that the backward computation time is overlapped by 2/3 and not overlapped by 1/3 from my perspective. However, I am uncertain about how Galvatron arrived at these specific numbers. What factors contribute to these numbers?

Additionally, in [tools/Galvatron/utils/cost_model_dist.py#L178](https://github.com/Hsword/Hetu/blob/6a501c9a57b036c19341122668e5678b55881173/tools/Galvatron/utils/cost_model_dist.py#L178), I observed that if the layer is an encoder, `self.bct` is multiplied by 1/2. This differs from the strategy [1,2,4]. Why is this the case?

Finally, why is it necessary for certain combinations of parallel strategies to consider the difference between encoder and decoder, while others do not? What distinguishes them?

I cannot find answers to them in Galvatron's paper and apologize for troubling you once again. Thank you very much!

**Comment by AFDWang** [comment]
These numbers are empirical coefficients obtained by observing the nsight timeline, which were introduced in order to obtain a more accurate cost model.
