### ISSUE TITLE
Questions about Environment Setup

### ISSUE THREAD

**Issue by Rmie9** [Hsword/Hetu#75]
Hello, I have encountered some issues while deploying the Hetu framework recently, and I hope you can offer some assistance. 
First, on one server, the compilation passes successfully, but when running the single-machine example, I encounter the error ImportError: anaconda3/envs/hetu/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so: symbol cusparseGetErrorString, version libcusparse.so.10 not defined in file libcusparse.so.10 with link time reference. How can this be resolved?
Additionally, on another server, the deployment fails during the compilation stage with errors in CUDA files, indicating missing files, domain-related errors, and other issues./home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(80): error: a class or namespace qualified name is required
/home/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(80): error: expected a ";"
/home/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(81): error: a class or namespace qualified name is required
/home/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(81): error: expected a ";"
...
Could these problems be due to version mismatches or other factors? I look forward to your reply. Thank you!

**Comment by Rmie9** [comment]
/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(80): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(80): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(81): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(81): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/block/specializations/../../block/../util_type.cuh(79): error: class "std::iterator_traits<<error-type>>" has no member "value_type"
          detected during:
            instantiation of type "cub::detail::value_t<<error-type>>" 
/home/antl/anaconda3/envs/hetu/include/cub/block/block_load.cuh(1295): here
            processing of template argument list for "cub::BlockLoadType" based on template arguments <Policy, <error-type>> 
/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(83): here

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(387): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(387): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(388): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(388): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(389): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(389): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(390): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_merge_sort.cuh(390): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/device/../iterator/arg_index_input_iterator.cuh(122): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/device/../iterator/arg_index_input_iterator.cuh(122): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/device/../iterator/arg_index_input_iterator.cuh(122): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/device/../iterator/arg_index_input_iterator.cuh(127): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/constant_input_iterator.cuh(105): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/constant_input_iterator.cuh(105): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/constant_input_iterator.cuh(105): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/constant_input_iterator.cuh(110): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_sub_warp_merge_sort.cuh(149): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_sub_warp_merge_sort.cuh(149): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_sub_warp_merge_sort.cuh(151): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_sub_warp_merge_sort.cuh(151): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/counting_input_iterator.cuh(103): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/counting_input_iterator.cuh(103): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/counting_input_iterator.cuh(103): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/device/dispatch/../../agent/../iterator/counting_input_iterator.cuh(108): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_adjacent_difference.cuh(71): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/agent/agent_adjacent_difference.cuh(71): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/cache_modified_output_iterator.cuh(136): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/iterator/cache_modified_output_iterator.cuh(136): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/iterator/cache_modified_output_iterator.cuh(136): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/cache_modified_output_iterator.cuh(141): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/iterator/discard_output_iterator.cuh(74): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/iterator/discard_output_iterator.cuh(74): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/iterator/discard_output_iterator.cuh(74): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/discard_output_iterator.cuh(79): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_obj_input_iterator.cuh(120): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_obj_input_iterator.cuh(120): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_obj_input_iterator.cuh(120): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_obj_input_iterator.cuh(125): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_ref_input_iterator.cuh(261): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_ref_input_iterator.cuh(261): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_ref_input_iterator.cuh(261): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/tex_ref_input_iterator.cuh(266): warning: parsing restarts here after previous syntax error

/home/antl/anaconda3/envs/hetu/include/cub/iterator/transform_input_iterator.cuh(126): error: a class or namespace qualified name is required

/home/antl/anaconda3/envs/hetu/include/cub/iterator/transform_input_iterator.cuh(126): error: global-scope qualifier (leading "::") is not allowed

/home/antl/anaconda3/envs/hetu/include/cub/iterator/transform_input_iterator.cuh(126): error: expected a ";"

/home/antl/anaconda3/envs/hetu/include/cub/iterator/transform_input_iterator.cuh(131): warning: parsing restarts here after previous syntax error

43 errors detected in the compilation of "/tmp/tmpxft_00000bb2_00000000-11_Argsort.compute_75.cpp1.ii".
src/CMakeFiles/c_runtime_api.dir/build.make:250: recipe for target 'src/CMakeFiles/c_runtime_api.dir/ops/Argsort.cu.o' failed
make[2]: *** [src/CMakeFiles/c_runtime_api.dir/ops/Argsort.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:183: recipe for target 'src/CMakeFiles/c_runtime_api.dir/all' failed
make[1]: *** [src/CMakeFiles/c_runtime_api.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Hsword** [comment]
Could you please try our latest version [here](https://github.com/PKU-DAIR/Hetu)?

**Comment by Rmie9** [comment]
sorry,my system and gpu cannot support the environment required by the new version.
